change logo
lalodiazdiaz/Emotions pull request #29
Opened 2023-01-03 22:26 UTC by lalodiazdiaz

2023-01-03 22:38 UTC, FraGa96 requested changes

2023-01-03 22:38 UTC, FraGa96 commented on src/components/Navbar/Navbar.module.css
> +.navItems{
Remove this empty classname, please

2023-01-03 22:57 UTC, FraGa96 approved these changes

2023-01-04 15:18 UTC, LuzLimon approved these changes

2023-01-04 15:22 UTC, merged