fix EM-3 errors ans add homePage
lalodiazdiaz/Emotions pull request #4
Opened 2022-11-25 19:35 UTC by lalodiazdiaz

2022-11-26 02:53 UTC, gfranco-arkus requested changes
Estas quitando todas las reglas que agregué a eslint, no lo haga compa

2022-11-26 04:03 UTC, gfranco-arkus approved these changes

2022-11-28 14:59 UTC, LuzLimon approved these changes

2022-11-28 15:01 UTC, LuzLimon approved these changes

2022-11-28 15:09 UTC, ErickIsra01 approved these changes

2022-11-28 15:10 UTC, merged