Em 158
lalodiazdiaz/Emotions pull request #45
Opened 2023-01-24 18:32 UTC by LuzLimon

2023-01-24 18:43 UTC, FraGa96 approved these changes

2023-01-24 18:43 UTC, FraGa96 commented on src/components/Psychologist/Dates/Dates.jsx
> +					}}
in order to improve readability, please create a function and use it here instead of create the anonymous function here

2023-01-24 18:44 UTC, FraGa96 requested changes

2023-01-24 18:44 UTC, FraGa96 commented on src/components/Psychologist/Dates/Dates.jsx
> +					}}
.

2023-01-25 18:00 UTC, FraGa96 approved these changes

2023-01-25 18:02 UTC, lalodiazdiaz approved these changes

2023-01-25 18:03 UTC, merged