Em 179
lalodiazdiaz/Emotions pull request #53
Opened 2023-01-30 18:44 UTC by lalodiazdiaz

2023-01-30 19:34 UTC, FraGa96 requested changes
Only missing accent marks c:

2023-01-30 19:34 UTC, FraGa96 commented on src/components/AdminTherapist/AddPsychologist/AddPsychologist.jsx
> +				<h2>Registro de psicologos</h2>
Registro de **psicólogos**
```suggestion
				<h2>Registro de psicólogos</h2>
```

2023-01-30 19:34 UTC, FraGa96 commented on src/components/AdminTherapist/AddPsychologist/AddPsychologist.jsx
> +										message: 'El telefono es un campo obligatorio',
El **teléfono** es un campo obligatorio
```suggestion
										message: 'El teléfono es un campo obligatorio',
```

2023-01-30 19:34 UTC, FraGa96 commented on src/components/AdminTherapist/AddPsychologist/AddPsychologist.jsx
> +										message: 'La cedula profesional es un campo obligatorio',
cédula
```suggestion
										message: 'La cédula profesional es un campo obligatorio',
```

2023-01-30 19:34 UTC, FraGa96 commented on src/components/AdminTherapist/AddPsychologist/AddPsychologist.jsx
> +							<option value="2">Psicologo</option>
Psicólogo
```suggestion
							<option value="2">Psicólogo</option>
```

2023-01-30 22:53 UTC, FraGa96 approved these changes

2023-01-31 00:37 UTC, LuzLimon approved these changes

2023-01-31 00:37 UTC, merged