EM 214
lalodiazdiaz/Emotions pull request #56
Opened 2023-02-01 17:58 UTC by LuzLimon

2023-02-01 18:36 UTC, FraGa96 requested changes

2023-02-01 18:36 UTC, FraGa96 commented on src/components/Psychologist/Patients/Patients.jsx
> +					</Link>
Remove the button
Leave only the link if you are going to change the route and style the link as a button

2023-02-02 16:16 UTC, FraGa96 approved these changes

2023-02-02 16:32 UTC, ErickIsra01 approved these changes

2023-02-02 16:32 UTC, merged