Em 22
lalodiazdiaz/Emotions pull request #7
Opened 2022-12-07 17:25 UTC by lalodiazdiaz

2022-12-07 18:15 UTC, ErickIsra01 submitted a review, later dismissed

2022-12-07 19:05 UTC, FraGa96 requested changes

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.jsx
> +const url = ' https://wa.me/526145153963';
I suggest use this as an env var or a constant in an external file like /src/constants.js

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.jsx
> +			<a href={url} target="_blanket">
did you mean "_blank"?

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.jsx
> +				<button
remove the button tag and style the anchor tag as button

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.jsx
> +				>Contactar
```suggestion
				>
				  Contactar
```

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.jsx
> +					>Agendar
```suggestion
					>
					  Agendar
```

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.module.css
>  .agendar:hover{
english please

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.module.css
> +.llamarPsicologo{
english please

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.module.css
> +.llamarPsicologo:hover{
english please x3

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.module.css
> +  .agendar{
english please x4

Check the file and use only english

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.module.css
> +  margin-right: 19px;
fix the indentation

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.module.css
> +  justify-content: center;
Fix the indentation

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.module.css
> +}
fix the indentation

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.jsx
> +			/>
```suggestion
			<Modal
				Content={contModal}
				onAction={modalCloseAction}
				style={modal}
				title="Consulta a tu psicologo"
			>
			 {contModal}
			</Modal>
```

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Home/Home.jsx
> +				Content={contModal}
use children instead

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Modal/Modal.jsx
> +function Modal({ style, onAction, title, Content }) {
```suggestion
function Modal({ style, onAction, title, children}) {
```

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Modal/Modal.jsx
> +				<Content />
```suggestion
				{children}
```

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Modal/Modal.module.css
> +.contact{
missing empty line, separate each class with an empty line

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Modal/Modal.module.css
> +}
fix indentation

2022-12-07 19:05 UTC, FraGa96 commented on src/components/Navbar/Navbar.jsx
> +					<button className={styles.btnLog} type="button">LogIn</button>
button is not required if it is already a Link

2022-12-08 17:55 UTC, FraGa96 requested changes

2022-12-08 17:55 UTC, FraGa96 commented on src/constants.js
> +export default URL;
this file is suposed to export multiple constants at one, don't use export default
use this instead
```
export const URL = ...
```

2022-12-08 18:08 UTC, FraGa96 approved these changes

2022-12-08 18:14 UTC, ErickIsra01 approved these changes

2022-12-08 18:15 UTC, merged