Em 20
lalodiazdiaz/Emotions pull request #9
Opened 2022-12-13 16:05 UTC by LuzLimon

2022-12-13 17:16 UTC, FraGa96 requested changes

2022-12-13 17:16 UTC, FraGa96 commented on src/store.jsx
> +// eslint-disable-next-line import/no-extraneous-dependencies, import/no-unresolved
why disable this?

2022-12-13 17:16 UTC, FraGa96 commented on .eslintrc.json
> +    "default-param-last": "off",
why disable this?

2022-12-13 17:16 UTC, FraGa96 commented on src/store.jsx
> +const store = createStore(
If you are going to use react-redux I highly recommend use redux-toolkit instead of the normal redux
[https://redux-toolkit.js.org/](url)

2022-12-14 16:31 UTC, FraGa96 requested changes, later dismissed
Use slices instead of traditional redux

2022-12-14 16:31 UTC, FraGa96 commented on src/components/Login/Login.jsx
> +						<input ref={checkBtn} style={{ display: 'none' }} />
avoid using inline styles

2022-12-16 15:45 UTC, lalodiazdiaz approved these changes

2022-12-16 15:46 UTC, MiguelAngelSF approved these changes

2022-12-16 15:49 UTC, MiguelAngelSF approved these changes

2022-12-16 15:50 UTC, merged